# docker-compose.yml

version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:5432/

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
    name: ${POSTGRES_DB}